config/routes.rb
Rails.application.routes.draw do
  resources :testings
    with_options only: [:index, :show, :create, :update, :destroy] do |list_only|
      list_only.namespace :api, path:'/', constraints:{subdomain:'api'} do
        resources :scientists, :events, :positions
        resources :groups do
          member do 
            resources :scientists, :events, :positions
          end
        end
      end
    end

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :group
	has_many :keyword_assignments, dependent: :destroy
	has_many :keywords, through: :keyword_assignments
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :scientists 
	has_many :events, dependent: :destroy
	has_many :positions, dependent: :destroy
	has_many :keyword_assignments, dependent: :destroy
	has_many :keywords, through: :keyword_assignments

	#scope :bla, where(abc: true) #where("age < 20") #where("created_at desc")

	#serialize :telephon
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	has_many :keyword_assignments
	has_many :groups, 	 through: :keyword_assignments 
	has_many :events, 	 through: :keyword_assignments 
	has_many :positions, through: :keyword_assignments 
	has_many :scientists, through: :keyword_assignments 
end

app/models/keyword_assignment.rb
class KeywordAssignment < ActiveRecord::Base
	belongs_to :group
	belongs_to :scientist
	belongs_to :event
	belongs_to :position
	belongs_to :keyword
end

app/models/position.rb
class Position < ActiveRecord::Base
	belongs_to :group
	has_many :keyword_assignments, dependent: :destroy
	has_many :keywords, through: :keyword_assignments
end

app/models/scientist.rb
class Scientist < ActiveRecord::Base
	belongs_to :group
	has_many :keyword_assignments, dependent: :destroy
	has_many :keywords, through: :keyword_assignments
end

app/models/testing.rb
class Testing < ActiveRecord::Base
end

app/controllers/api/groups_controller.rb
module API
	class GroupsController < ApplicationController
		before_action :get_obj, only: [:show, :edit, :update, :destroy]
		
		def serializer_name
			#returns all the groubs including their relations. e.g., scientists & events
			if params[:detail] 
				serializer_name = GroupDetailSerializer
			#returns group's scientists
			elsif params[:scientists]
			elsif params[:events]
			elsif params[:positions]	
			else 
				serializer_name = GroupSerializer
			end
		end

		def index
			@groups = Group.all
			create_respond @groups, serializer_name
		end

		def show
			if scientists = params[:scientists]
				@group = 
			create_respond @group, serializer_name
		end

		def get_obj
			@group = Group.find(params[:id])
		end


	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def create_respond(resource, serializer_name) 
	respond_to do |format|
		format.json {render json: resource, serializer: serializer_name} #, meta: {total: 10}
	end
  	
  end
end

app/controllers/testings_controller.rb
class TestingsController < ApplicationController
  before_action :set_testing, only: [:show, :edit, :update, :destroy]

  # GET /testings
  # GET /testings.json
  def index
    @testings = Testing.all
  end

  # GET /testings/1
  # GET /testings/1.json
  def show
  end

  # GET /testings/new
  def new
    @testing = Testing.new
  end

  # GET /testings/1/edit
  def edit
  end

  # POST /testings
  # POST /testings.json
  def create
    @testing = Testing.new(testing_params)

    respond_to do |format|
      if @testing.save
        format.html { redirect_to @testing, notice: 'Testing was successfully created.' }
        format.json { render :show, status: :created, location: @testing }
      else
        format.html { render :new }
        format.json { render json: @testing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testings/1
  # PATCH/PUT /testings/1.json
  def update
    respond_to do |format|
      if @testing.update(testing_params)
        format.html { redirect_to @testing, notice: 'Testing was successfully updated.' }
        format.json { render :show, status: :ok, location: @testing }
      else
        format.html { render :edit }
        format.json { render json: @testing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testings/1
  # DELETE /testings/1.json
  def destroy
    @testing.destroy
    respond_to do |format|
      format.html { redirect_to testings_url, notice: 'Testing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testing
      @testing = Testing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testing_params
      params[:testing]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/testings_helper.rb
module TestingsHelper
end

app/views/groups/index.html.erb
<h1>hi</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forsker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/testings/_form.html.erb
<%= form_for(@testing) do |f| %>
  <% if @testing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testing.errors.count, "error") %> prohibited this testing from being saved:</h2>

      <ul>
      <% @testing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testings/edit.html.erb
<h1>Editing Testing</h1>

<%= render 'form' %>

<%= link_to 'Show', @testing %> |
<%= link_to 'Back', testings_path %>

app/views/testings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testings.each do |testing| %>
      <tr>
        <td><%= link_to 'Show', testing %></td>
        <td><%= link_to 'Edit', edit_testing_path(testing) %></td>
        <td><%= link_to 'Destroy', testing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testing', new_testing_path %>

app/views/testings/new.html.erb
<h1>New Testing</h1>

<%= render 'form' %>

<%= link_to 'Back', testings_path %>

app/views/testings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_testing_path(@testing) %> |
<%= link_to 'Back', testings_path %>